export const karleyTestimony =
  "Erin was a wonderful coordinator for our wedding! She was always courteous and detail-oriented. She kept things running smoothly/on-time from rehearal speeches and practice to photography and the actual wedding. As a DIY bride, I had so many little details that I'd planned and scheduled, Erin allowed me to sit back and enjoy our wedding without worry. There was not a single request she didn't see to or address herself! A true pro! Couldn't have done it without Erin!";

export const alyssaTestimony =
  "Erin Wiltse was invaluable at our wedding and exceeded all of our expectations. After drawing up our basic outline, we met with Erin to discuss the details. She clarified questions we had not yet considered and created schedules and outlines for all of the wedding events. Her confidence gave us assurance and encouragement that we would not have to worry about a thing. Our wedding party, officiant, and family members all received clear direction before, during, and after the ceremony. Her gifts in organization and directing were truly on display throughout the process. Once the cameras were on, she quickly garnered the respect and attention of the entire bridal party. Our wedding and photos went without a hitch, thanks largely to Erin's guidance. Our parents were blessed to simply enjoy the wedding and leave the details to Erin. Throughout the entire day, my thoughts were free from worry, allowing me to enjoy the blessings at hand and the wonderful gift of marriage to my husband.";

export const hannahTestimony =
  'I have seen Erin use her gifts of leadership, delegation, and detail in many different avenues; whether it was organizing my wedding party, a community wide event, or just a game night with friends. She is passionate, driven, energetic and consistent. She has capacity to execute so many things well.  She is an unforgettable person who is loved by so many.';

export const whitneyTestimony =
  "Erin did a fabulous job coordinating our wedding. Because of her, the events during our wedding weekend went so smoothly. I didn't have to worry about a thing because I knew she had it covered. Erin was excellent at taking care of even the smallest details so that I wasn't stressed about anything to do with the event itself. Not only was she great at coordinating, she is personable, warm, and worked well with my family and friends to help them feel at ease throughout the day. I am so thankful for all of Erin's work to help us have the BEST day ever!";

export const jesseTestimony =
  "Erin was amazing! She took an immense amount of stress off of my family and I. I did not have to worry about anything going wrong due to Erin being diligent and organized. She went over all the schedules and outlines and made sure there was adequate time for it all, plus added in multiple essential things I would have never thought of. Erin made the wedding day go smooth, and even gently modified plans to keep my wishes and the guests happy! Also, you can't miss it- she brings life to any party!";

export const coriTestimony =
  "Erin was amazing! She took an immense amount of stress off of my family and I. I did not have to worry about anything going wrong due to Erin being diligent and organized. She went over all the schedules and outlines and made sure there was adequate time for it all, plus added in multiple essential things I would have never thought of. Erin made the wedding day go smooth, and even gently modified plans to keep my wishes and the guests happy! Also, you can't miss it- she brings life to any party!";

export const meganTestimony =
  "Erin was such a blessing to have during our big weekend. We met with her before the day & ran through everything with her; she has such an eye for detail from past experiences that she was able to ask us questions to help sketch out every little detail of our wedding. Our day went so smooth because of that - we didn't have to worry about anything! Her direct, assertive personality helped corral people during our rehearsal dinner and our wedding day. During our wedding rehearsal, she addressed everybody so that we were all on the same page going into the weekend. I felt like I could just enjoy my weekend & celebrate us and our relationships, and we didn't have to worry about how the wedding was going. Thank you, Erin, for being our day-of coordinator!";

export const katieTestimony =
  'Erin was absolutely amazing as our wedding coordinator. We met up a few months before the wedding and I discussed with her the wedding schedule and gave her all the layouts for the day of. The day before she led the rehearsal dinner by making sure the musicians and wedding party knew timing and their positions. She did a great job of handling my large and boisterous wedding party (9 groomsmen and 9 bridesmaids plus 2 three year olds). Erin came the morning of and handled vendors coming in and doing the final touches on the ceremony set up. It was great having her handle what would be stressful situations for the bride and family. My wedding took place in the same venue as the reception so we knew we needed good leadership to make the flip happen as quickly as possible. Erin handled this with ease and the reception was set up and ready to go before we were done with pictures! Erin is the coordinator for you if you are looking for someone who can direct large groups of people and handle pressured situations with flexibility.';

export const robynTestimony =
  'Erin is one of the most fun people I have ever met! Not only did she keep things lighthearted and enjoyable, but she stayed on top of the schedule and provided much needed organization! She is a natural leader and has a great voice that people follow. She was an amazing coordinator for our special day! ';

export const janieTestimony =
  'Erin was so helpful coordinating our wedding day! She took care of every detail and handled anything that came up. I felt so at peace knowing someone was making sure all things were happening and I could just focus on getting married.';
