export const FETCH_NEW_CONTACT = "FETCH_NEW_CONTACT";
export const FETCH_USER = "FETCH_USER";
export const FETCH_ADMIN = "FETCH_ADMIN";
export const ADMIN_SIGNED_IN = "ADMIN_SIGNED_IN";
export const ADMIN_SIGNED_OUT = "ADMIN_SIGNED_OUT";
export const SET_HEIGHT = "SET_HEIGHT"